[tools]

# Linters
"aqua:grafana/flint" = "0.22.2"
lychee = "0.24.2"

[env]
FLINT_CONFIG_DIR = ".github/config"
MISE_AQUA_REGISTRY_URL = "https://github.com/aquaproj/aqua-registry"

[tasks.links]
description = "Check links"
run = "flint run"
